name: Code Coverage Report
description: Generate a HTML body with the code coverage
author: Romeo Van Snick
branding:
  icon: check-square
  color: green
inputs:
  lcov-file:
    description: The location of the lcov.info file
    required: false
    default: ./coverage/lcov.info
  lcov-base:
    description: The location of the lcov file for the base branch
    required: false
  path:
    description: 'The destination path the HTML body file'
    required: false
    default: ./coverage/body.html
runs:
  using: node12
  main: dist/main.js
